# Generated by Django 4.2 on 2023-05-25 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_homepageproductvegetable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepageproductvegetable',
            old_name='product_id',
            new_name='vege_id',
        ),
    ]
