# Generated by Django 4.2 on 2023-05-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_dealsweek'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigPackBiggerDiscount',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
                ('product_name', models.CharField(max_length=50)),
                ('per_off', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('price', models.CharField(max_length=30)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
