# Generated by Django 4.2 on 2023-05-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerServiceRequest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=150)),
                ('addressline2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=12)),
                ('State', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=6)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
    ]
